import React from 'react';
import Head from 'next/head'
import styles from "./Layout.module.css";
import Link from "next/link";
import Logo from "./logo.js";
import Brightness6Icon from '@mui/icons-material/Brightness6';

const Layout = ({children}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>World Ranks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <Link href="/">
            <Logo/>
        </Link>
        <button className={styles.modeBtn} >
            <Brightness6Icon/>
        </button>
      </header>
      <main className={styles.main}>
       {children}
      </main>
      <footer className={styles.footer}>
        The WorldRannks @worldranks.io
      </footer>
    </div>
  )
}

export default Layout